### ISSUE TITLE
Fix Pending Posts on Prod

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/admithub-telescope-theme#39]
Currently all posts still appear in pending posts...

not sure why

**Comment by pcorey** [comment]
It looks like the pending/approved process is working in Prod.

An issue I found is that when you click "Load More" at the bottom of pending, it actually redirects you to "https://college.admithub.com/top/20" instead of "https://college.admithub.com/pending/20". This made it look like all of the approved posts were actually in the Pending section.

I fixed the bug that was causing this and pushed the change to production. It looks to be working correctly now.

Let me know if there's something I'm missing here...

**Comment by AndrewMagliozzi** [comment]
I'm still seeing a ton of already approved questions in "pending" on prod...

**Comment by pcorey** [comment]
If you give me a few links to posts that are showing up as Pending, but should be approved I can dig into what's going on.

**Comment by AndrewMagliozzi** [comment]
Hey Pete, did you see the links I sent to you on Slack?

**Comment by pcorey** [comment]
Yeah,

I haven't had a change to dig into them yet.

For posterity:
https://college.admithub.com/posts/peYwHtM4HKdgWKA9m/p/will-a-great-personal-statement-help-me-if-i-have-a-2-5-2-8-gpa-for-uc-admissions-
https://college.admithub.com/posts/PEk4nfMYvvC4tvqFH/p/will-a-great-personal-statement-help-me-if--i-have-a-2-5-2-8-gpa-

**Comment by pcorey** [comment]
We removed all pending posts. Re-open this if more dupes pop up.
